on:
  push:
    tags:
      - 'cbmc-*'

name: Create Release

jobs:
  get-version-information:
    name: Get Version Information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.split.outputs._2 }}
    steps:
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.ref }}
          seperator: '/'
  perform-release:
    name: Perform Release
    runs-on: ubuntu-20.04
    needs: get-version-information
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          CBMC_TAG: ${{ needs.get-version-information.outputs.version }}
        with:
          tag_name: ${{ env.CBMC_TAG }}
          release_name: ${{ env.CBMC_TAG }}
          body: |
            This is CBMC version ${{ env.CBMC_TAG }}.

            ## MacOS

            On MacOS, install CBMC using [Homebrew](https://brew.sh/) with

            ```sh
            brew install cbmc
            ```

            or upgrade (if it's already been installed) with:

            ```sh
            brew upgrade cbmc
            ```

            ## Ubuntu

            On Ubuntu, install CBMC by downloading the *.deb package below for your version of Ubuntu and install with one of

            ```sh
            # Ubuntu 18:
            $ dpkg -i ubuntu-18.04-${{ env.CBMC_TAG }}-Linux.deb
            # Ubuntu 20:
            $ dpkg -i ubuntu-20.04-${{ env.CBMC_TAG }}-Linux.deb
            ```

            ## Windows

            On Windows, install CBMC by downloading the `${{ env.CBMC_TAG }}-win64.msi` installer below, double-clicking on the installer to run it, and adding the folder `C:\Program Files\cbmc\bin` in your `PATH` environment variable.

            For installation from the windows command prompt, run:

            ```sh
            msiexec /i ${{ env.CBMC_TAG }}-win64.msi
            PATH="C:\Program Files\cbmc\bin";%PATH%
            ```

            Note that we depend on the Visual C++ redistributables. You likely already have these, if not please download and run vcredist.x64.exe from Microsoft to install them prior to running cbmc, or make sure you have Visual Studio 2019 installed.

            You can download either [Visual Studio 2019 Community Edition](https://visualstudio.microsoft.com/vs/community/) or the [Visual C++ Redistributables](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads) from Microsoft for free.
          draft: false
          prerelease: false
